// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzAZi4r35LNkMheQ4FDmznPxgyrrqz7gA',
    appId: '1:389656977546:web:f8a7a606d9fa1b3ed54d73',
    messagingSenderId: '389656977546',
    projectId: 'appflutter-b0b86',
    authDomain: 'appflutter-b0b86.firebaseapp.com',
    storageBucket: 'appflutter-b0b86.appspot.com',
    measurementId: 'G-EE0JRLWS57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Sh5Bk5muOp_U2R9v8nHyoX0-w1j7Dzs',
    appId: '1:389656977546:android:1f1f773774267351d54d73',
    messagingSenderId: '389656977546',
    projectId: 'appflutter-b0b86',
    storageBucket: 'appflutter-b0b86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfk3DCgEmkauybGEp8veyPAoMN-daaSk',
    appId: '1:389656977546:ios:e6a6d9a19894e183d54d73',
    messagingSenderId: '389656977546',
    projectId: 'appflutter-b0b86',
    storageBucket: 'appflutter-b0b86.appspot.com',
    iosClientId: '389656977546-ubdvg1abk7tgc0ov2fj7d0k5n162o37r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfk3DCgEmkauybGEp8veyPAoMN-daaSk',
    appId: '1:389656977546:ios:aaabb487e63fcc60d54d73',
    messagingSenderId: '389656977546',
    projectId: 'appflutter-b0b86',
    storageBucket: 'appflutter-b0b86.appspot.com',
    iosClientId: '389656977546-c2u8vpks3f9l5ddtdp03tb1b8m21flpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestapp.RunnerTests',
  );
}
